# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'NetworkCourseWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Kingfisher'
  # Pods for NetworkCourseWork

end
