# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'networkFirstTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Kingfisher'

  # Pods for networkFirstTask

end
